### ISSUE TITLE
Free GitHub key not working

### ISSUE THREAD

**Issue by david-sfernandes** [NopeCHALLC/nopecha-nodejs#12]
Hi,

I’m trying to experiment with NopeCHA to see how it works, and I noticed that you offer an option to generate a free key using a GitHub account.

I created this free key, but when I made a request with it to solve a `recaptcha2`, I received an error saying: `Feature unavailable for current plan.`

I couldn’t find any information in the documentation regarding the limitations of the free key.

What is the limitations for this type of key?

**Comment by azizfcb** [comment]
same

**Comment by AlyonaPianykh** [comment]
Hello team @NopeCHALLC!
I'm facing same issue both for Github key and Discord key.
How can I overcome this problem for development environment?

**Comment by david-sfernandes** [comment]
Well, it looks like this project no longer has support. I will close this issue without a solution, as I am already using another service. Unfortunately, I cannot recommend this library due to the lack of support.
